# Generated by Django 5.0.4 on 2024-05-06 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_student_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name_plural': 'names'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_link',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='testdb.subject'),
            preserve_default=False,
        ),
    ]
