# Generated by Django 5.0.4 on 2024-05-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_subject_options_teacher_subject_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_link',
            field=models.ManyToManyField(to='testdb.subject'),
        ),
    ]
