# Generated by Django 5.0.4 on 2024-05-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_remove_teacher_subject_link_teacher_subject_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='testdb.subject'),
        ),
    ]
