# Generated by Django 5.0.4 on 2024-05-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_remove_teacher_subject_link_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name', 'age']},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjects',
        ),
    ]
