# Generated by Django 5.0.4 on 2024-05-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_alter_subject_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Please specify', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='testdb.subject'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emblem', models.CharField(max_length=50)),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testdb.teacher')),
            ],
        ),
    ]
