# Generated by Django 5.0.4 on 2024-05-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_student_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='founder',
            field=models.CharField(default='Please update', max_length=80),
            preserve_default=False,
        ),
    ]
